"""add profile fields

Revision ID: 7bf98e04472e
Revises: 2f7244f99b97
Create Date: 2026-06-06 07:53:58.284423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bf98e04472e'
down_revision: Union[str, Sequence[str], None] = '2f7244f99b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('user_profiles', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('professional_title', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('email', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('projects', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('user_profiles', sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('user_profiles', sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('user_profiles', sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'links')
    op.drop_column('user_profiles', 'languages')
    op.drop_column('user_profiles', 'education')
    op.drop_column('user_profiles', 'projects')
    op.drop_column('user_profiles', 'email')
    op.drop_column('user_profiles', 'professional_title')
    op.drop_column('user_profiles', 'full_name')
    # ### end Alembic commands ###
